config/routes.rb
TestApp::Application.routes.draw do

  resources :posts, only: [:create]
  resource :search, only: [:show] do
    member do
      get "tag" => "searches#tags"
    end
  end
  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :update, :show]

  match "/admin", to: "dashboards#admin"
  match "/dashboard", to: "dashboards#index"
  match "/new", to: "posts#new"
  match "/edit/:id", to: "posts#edit"
  post "/preview", to: "posts#preview"
  put "/preview", to: "posts#preview"
  get "/:slug", to: "posts#show", as: "post"
  delete "/:slug", to: "posts#destroy", as: "post"
  put "/:slug", to: "posts#update", as: "post"
  root to: "users#new"


end

app/models/guest.rb
class Guest
  def error
  end
  def id
    false
  end

  def username
    "Welcome Guest"
  end

  def admin
    false
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :tag_list, :title, :slug, :content, :url, :draft
  acts_as_ordered_taggable
  acts_as_url :title, :url_attribute => :slug
  belongs_to :user

  validates :title, presence: true
  validates :slug, presence: true, uniqueness: true

  default_scope order('created_at desc')

  def to_param
    slug
  end

  def external?
    url.present?
  end

  def has_more_tag
    content =~ /<!--\s*more\s*-->/i ? true : false
  end

  def excerpt
    if content.index(/<!--\s*more\s*-->/i)
      content.split(/<!--\s*more\s*-->/i)[0]
    else
      content
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :posts

  attr_accessible :admin, :password, :password_confirmation, :email,
                  :github, :twitter, :username

  validates :password, presence: { on: :create }
  validates :username, presence: true, uniqueness: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :popular_tags
  protect_from_forgery
  helper_method :current_user, :signed_in, :is_admin

  def current_user
    if (session[:user_id])
      User.find(session[:user_id])
    else
      Guest.new
    end
  end

  def is_admin
    if current_user.admin == true
      true
    else
      false
    end
  end

  def popular_tags
    @tags = ActsAsTaggableOn::Tag.most_used(10)
  end

  def signed_in
    unless current_user.id
      false
    else
      true
    end
  end

  def authenticate_admin
    unless is_admin
      redirect_to root_path
    end
  end

  def authenticate_user
    unless signed_in
      redirect_to root_path
    end
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_filter :authenticate_admin, only: [:admin]
  before_filter :authenticate_user, only: [:admin, :index]

  def admin
    @user = current_user
    @posts = Post.order(:created_at => :desc).page(params[:page]).per(5)
  end

  def index
    @user = current_user
    @posts = current_user.posts.page(params[:page]).per(5)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authenticate_user
  before_filter :authorize_user, only: [:delete]

  def index
    @posts = Post.page(params[:page]).per(10).where(draft:false)
  end

  def preview
    @post = Post.new(params[:post])
    @preview = true
    render :show
  end

  def show
    @single_post = true
    @post = Post.find_by_slug(params[:slug])
  end

  def new
    @post = Post.new
  end

  def edit
    @no_header = true
    @post = Post.find(params[:id])
  end

  def create
    @post = current_user.posts.new(params[:post])
    generate_tags

    if @post.save
      redirect_to dashboard_path
    else
      redirect_to :new
    end
  end

  def update
    @post = Post.find_by_slug(params[:slug])

    if @post.update_attributes(params[:post])
      generate_tags
      redirect_to dashboard_path, notice: "Post updated successfully"
    else
      redirect_to post_path(@post.id), action: :edit
    end
  end

  def destroy
    @post = Post.find_by_slug(params[:slug])
    @post.destroy

    redirect_to :back
  end

  private

  def generate_tags
    if params[:post][:tag_list]
      @post.tag_list.remove(params[:post][:tag_list])

      (params[:post][:tag_list]).to_s.split(/\s+/).each do |tag|
        @post.tag_list.add(tag.downcase).uniq
      end
    end
  end

  def authorize_user
    unless (@post.user_id == current_user.id || is_admin)
      redirect_to :back
    end
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def show
    searchposts = Post.find(:all, :conditions =>
                       ["content LIKE ? Or title LIKE ?",
                        "%#{params[:search]}%","%#{params[:search]}%"])
    @posts = Kaminari.paginate_array(searchposts).page(params[:page]).per(5)
  end

  def tags
    @posts = Post.tagged_with(params[:tag]).page(params[:page]).per(4)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_username(params[:session][:username])
    if user.authenticate( params[:session][:password] )
      session[:user_id] = user.id
      if user.admin
        redirect_to admin_path
      else
        redirect_to dashboard_path
      end
    else
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    user = User.new(params[:user])
    
    if user.save
      session[:user_id] = user.id
      if user.admin
        redirect_to admin_path
      else
        redirect_to dashboard_path
      end
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.page(params[:page]).per(4)
  end

  def update
    user = User.find(params[:id])

    if user.update_attributes(params[:user])
      redirect_to dashboard_path
    else
      redirect_to :back
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def is_admin?
    true if session[:admin] == true
  end

  def markdown(text)
    text = youtube_embed(text)
    text = gist_embed(text)
    RedcarpetCompat.new(text, :fenced_code, :gh_blockcode)
  end

  # TODO refactor these filters so they don't each iterate over all the lines
  def gist_embed(str)
    output = str.lines.map do |line|
      match = nil
      match = line.match(/\{\{gist\s+(.*)\}\}/)
      match ? "<div id=\"#{match[1]}\" class=\"gist\">Loading gist...</div>" : line
    end
    output.join
  end

  def youtube_embed(str)
  	output = str.lines.map do |line|
  		match = nil
  		match = line.match(/^http.*(?:youtu.be\/|v\/|u\/\w\/|embed\/|watch\?v=)([^#\&\?]*).*/)
  		match ? render(:partial => 'youtube', :locals => { :video => match[1] }) : line
  	end
  	output.join
  end
end

app/helpers/page_title_helper.rb
module PageTitleHelper
  def html_title(content)
    if content.present?
      [content,CONFIG['title']].join(' - ')
    else
      CONFIG['title']
    end
  end

  def page_title(content)
    @title = content || CONFIG['title']
    render partial: 'title'
  end

  def linked_title
    link_to CONFIG['title'], root_path
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  include ActsAsTaggableOn::TagsHelper
end

app/views/application/_title.html.erb
<h1><%= link_to @title, root_path %></h1>

app/views/application/_youtube.html.erb
<div class="youtube_video">
  <object width="640" height="365">
    <param name="movie" value="http://www.youtube.com/v/<%= video %>&hl=en"></param>
    <param name="wmode" value="transparent"></param>
    <embed src="http://www.youtube.com/v/<%= video %>&hl=en" type="application/x-shockwave-flash" wmode="transparent" width="640" height="365"></embed>
  </object>
</div>

app/views/dashboards/_admin.html.erb
<section>
  <div class="post contain">
      <h1 class="external">
      </h1>
      <ul>
        <fieldset>
          <li>
            <div>Post Title:
              <%= link_to post.title, post_path(post), method: :get %></div>
            Post Created At: 
            <time><%= post.created_at.to_formatted_s(:day_month_year) %></time>
          </li>
          <li>
            <%= link_to "Delete Post", post_path(post), method: :delete %>
          </li>
      </ul>
  </div>
</section>

app/views/dashboards/admin.html.erb
<div class="contentcontainer">
  <h2>Welcome Administrator <%= current_user.username %></h2>

  <div class="userposts">
    <h3>Users Blog Posts</h3>
    <div>
      <%= render :partial => "admin", :collection => @posts, :as => :post %>
      <%= paginate @posts %>
    </div>
  </div>
</div>

app/views/dashboards/index.html.erb
<div class="contentcontainer">
  <h2> <%= "Welcome to your Dashboard, #{@user.username}" %> </h2>

  <div>
    <div class="links">
      <h3>Your Links</h3>
      <div>
        <%= link_to "Edit Twitter: #{@user.twitter}" %>
      </div>
      <div>
        <%= link_to "github", "https://github.com/#{@user.github}" %>
      </div>
      <div>
        <%= link_to "email", "mailto:#{@user.email}?subject:hello" %>
      </div>
      <div>
        <%= link_to "rss feed", "/posts.rss" %>
      </div>
    </div>

    <div class="editaccount">
      <h3>Edit Your Account Details</h3>
      <%= form_for @user do |f| %>
        <fieldset>
          <%= f.label "Twitter" %>
          <%= f.text_field :twitter, placeholder: "#{@user.twitter}" %>
        </fieldset>
        <fieldset>
          <%= f.label "GitHub" %>
          <%= f.text_field :github, placeholder: "#{@user.github}" %>
        </fieldset>
        <fieldset>
          <%= f.label "Email" %>
          <%= f.text_field :email, placeholder: "#{@user.email}" %>
        </fieldset>
        <div>
          <%= f.submit "Update Account" %>
        </div>
      <% end %>
    </div>

    <div class="userposts">
      <h3>Your Blog Posts</h3>
      <ul>
        <li>
          <%= button_to "Create Post", new_path, method: :get %>
        </li>
        <% @posts.each do |post| %>
          <fieldset>
            <li>
            <%= link_to post.title, post_path(post) %>
            </li>
            <li>
            <%= link_to "Edit Post", post_path(post), method: :edit %>
            </li>
            <li>
              <%= link_to "Delete Post", post_path(post), method: :delete %>
            </li>
            <li>
              <time>
                <%= post.created_at.to_formatted_s(:day_month_year) %>
              </time>
            </li>
          </fieldset>
        <% end %>
        <%= paginate @posts %>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/admin.html.erb
<!doctype html>
<html lang="en-US">
<head>
  <title><%= html_title yield(:title) %></title>
  <%= csrf_meta_tag %>
  <%= stylesheet_link_tag 'application' %>
  <link href='http://fonts.googleapis.com/css?family=Lato:300,900' rel='stylesheet' type='text/css' />
</head>

<body class="admin <%= controller_name %> <%= action_name %>">
  <div id="admin">
  	<div id="save"></div>
    <% if notice %><span class="notice"><%= notice %></span><% end %>
    <%= yield %>
  </div>

  <%= javascript_include_tag 'application' %>
</body>
</html>

app/views/layouts/application.html.erb
<html>
  <head>
    <title>Bloggr</title>
    <%= csrf_meta_tag %>
    <%= stylesheet_link_tag "application", media: "all" %>
    <link href="/posts.rss" rel="alternate" title="RSS" 
          type="application/rss+xml" />
    <link href="http://fonts.googleapis.com/css?family=Lato:300,900"
          rel="stylesheet" type="text/css" />
    <%= javascript_include_tag "application" %>
  </head>

  <header class="header">
    <div class="title">
      <h1>
        <%= link_to "Bloggr", root_url %> ~~~ A Blogging Application
      </h1>
    </div>

    <div class="navigation">
      <ul class="login">
        <% if signed_in %>
          <li>
            <%= link_to "Sign Out", session_path, method: :delete %>
          </li>
          <li>
            <%= link_to "My Dashboard", dashboard_path %>
          </li>
          <% if is_admin %>
            <li>
              <%= link_to "Admin Page", admin_path %>
            </li>
          <% end %>
        <% else %>
          <li>
            <%= link_to "Sign In", new_session_path %>
          </li>
          <li>
            <%= link_to "Sign Up", new_user_path %>
          </li>
        <% end %>
      </ul>
    </div>
  </header>

  <nav class="sidebar">
    <%= form_tag search_path, method: :get do %>
      <%= search_field_tag :search, params[:search],
          placeholder: "SEARCH" %>
    <% end %>
    <ul>
      <h4>Recent Tags</h4>
      <% @tags.each do |tag| %>
        <li>
          <%= link_to tag.name, tag_search_path(:tag => tag.name) %>
        </li>
      <% end %>
    </ul>
  </nav>

  <body class="container">
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<div class="postcontainer">
  <%= form_for @post do |f| %>
    <div id="split">
      <div id="post-editor" class="split-section">
        <%- if @post.errors.any? -%>
          <div class="notice">
            <%- @post.errors.full_messages.each do |msg| -%>
              <%= msg %>
            <%- end -%>
          </div>
        <%- end -%>
        <%= link_to '⚓', @post, :class => 'permalink',
                    :target => '_blank' if @post.slug %>
        <div id="text-title" class="expandingArea">
          <pre><span></span><br></pre>
            <%= f.text_area :title, :rows => 1, :placeholder => 'Title here' %>
        </div>
        <fieldset class="markdown">
          <div id="text-content" class="expandingArea">
            <pre><span></span><br></pre>
            <%= f.text_area :content, :placeholder => "Write post here",
                size: "40x40" %>
          </div>
        </fieldset>
      </div>
      <div id="post-preview" class="split-section">
      </div>
    </div>

    <div id="publish-bar-hover">
      <div id="publish-bar">
        <div class="contain">
          <div class="left">
            <a href="/admin">&laquo; Admin</a>
            <%= link_to 'Delete', @post, :confirm => 'Are you sure?',
                :method => :delete, :class => 'delete-bar' %>
            <%= link_to 'Options', '#options', :class => 'menu' %>
            <ul id="options" class="sub-menu">
              <li>
                <%= f.label :tag_list, "Tagging!" %>
                <%= f.text_field :tag_list,
                    placeholder: "Put a space between each tag" %>
              </li>
              <li>
                <%= f.label :url, 'Slug' %>
                <%= f.text_field :slug, 
                    :placeholder => 'Leave blank to automatically generate' %>
              </li>
              <li>
                <%= f.label :url, 'URL' %>
                <%= f.text_field :url,
                    :placeholder => 'Optional external link' %>
              </li>
            </ul>
          </div>
          <div class="right">
            <%= f.label :draft %>
            <%= f.check_box :draft %>
            <%= f.submit 'Preview', :id => 'preview-button', :preview => true,
                :target => "_blank" %>
            <%= f.submit 'Save', :id => 'save-button' %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/posts/_li.html.erb
<li id="post-<%= li.id %>">
	<h3>
		<%= link_to li.title, '/edit/' + li.id.to_s %>
		<span class="links">
			<%= link_to 'view', li, :class => 'admin-view' %>
			<%= link_to 'x', li, :confirm => 'Are you sure?', :method => :delete, :class => 'admin-delete' %>
		</span>
	</h3>
</li>

app/views/posts/_post.html.erb
<section id="post-<%= post.id %>">
  <div class="post contain">
    <%- if post.external? -%>
      <h1 class="external">
        <% if @single_post %><%= link_to post.title, post.url %><% else %><%= link_to post.title, post.url %><% end %>
        <%= link_to '⚓', post.slug, :class => 'permalink' %>
      </h1>
    <%- else -%>
      <h1><% if @single_post %><%= post.title %><% else %><%= link_to post.title, post.slug %><% end %></h1>
    <%- end -%>

    <% if post.has_more_tag && !@single_post && !@preview %>
      <% if post.excerpt %><%= markdown(post.excerpt).to_html.html_safe %><% end %>
	    <%= link_to "Continue Reading →", post.slug, :class => "button" %>
    <% else %>
      <% if post.content %><%= markdown(post.content).to_html.html_safe %><% end %>
    <% end %>

    <%- if is_admin? -%>
      <ul class="actions">
        <li><%= link_to 'Edit', '/edit/' + post.id.to_s unless @preview %></li>
      </ul>
    <%- end -%>
  </div>

  <%= link_to "Back", :back %>
</section>

app/views/posts/admin.html.erb
<div id="drafts" class="col">
  <h1>Drafts <%= link_to 'New Draft', '/new', :class => 'button' %></h1>
  <%= form_for @post do |f| %>
    <%= f.text_field :title, :placeholder => 'Start typing your title here...' %>
  <% end %>
  <ul>
  <%= render :partial => 'li', :collection => @drafts %>
  </ul>
  <%= paginate @drafts, :param_name => "draft_page" %>
</div>

<div id="published" class="col">
  <h2>Published <%= link_to 'Home', root_url, :class => 'button' %></h2>
  <ul>
    <%= render :partial => 'li', :collection => @published %>
  </ul>
  <%= paginate @published, :param_name => "post_page" %>
</div>

app/views/posts/edit.html.erb
<%= render 'form' %>

app/views/posts/index.html.erb
<%= session[:text] %>
<%= render @posts %>
<%= paginate @posts %>

app/views/posts/new.html.erb
<% content_for(:title) do -%>
  Admin
<% end %>

<%= render 'form' %>

app/views/posts/show.html.erb
<div class="postscontent">
  <div>
    <%- content_for(:title) { @post.title } -%>
    <%- content_for(:page_title) { linked_title } -%>
  </div>
  <div class="showpost">
    <%= render @post %>
  </div>
</div>

app/views/searches/show.html.erb
<div class="searchcontainer">
  <ul>
    <% @posts.each do |post| %>
      <fieldset>
        <li>
          <div>Post Title:
            <%= link_to post.title, post_path(post), method: :get %></div>
          Post Created At: 
          <time><%= post.created_at.to_formatted_s(:day_month_year) %></time>
        </li>
        <li>
          Tags For Post: <%= post.tag_list %>
        </li>
        <li>
          Created By: <%= link_to post.user.username, post.user %>
        </li>
      </fieldset>
    <% end %>
  </ul>
  <%= paginate @posts %>
</div>

app/views/searches/tags.html.erb
<div class="searchcontainer">
  <ul>
    <% @posts.each do |post| %>
      <fieldset>
        <li>
          <div>Post Title:
            <%= link_to post.title, post_path(post), method: :get %></div>
          Post Created At: 
          <time><%= post.created_at.to_formatted_s(:day_month_year) %></time>
        </li>
        <li>
          Tags For Post: <%= post.tag_list %>
        </li>
        <li>
          Created By: <%= link_to post.user.username, post.user %>
        </li>
      </fieldset>
    <% end %>
  </ul>
  <%= paginate @posts %>
</div>

app/views/users/new.html.erb
<div class="innercontainer">
  <% if @user.errors.any? %>
    <div>
      <h2>Form Invalid</h2>
      <ul>
        <% @user.errors.full_messages do |message| %>
          <li>
            <%= message %>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form_for @user do |f| %>
    <fieldset>
    <%= f.label :username %>
    <%= f.text_field :username %>
    </fieldset>
    <fieldset>
      <%= f.label :password %>
      <%= f.password_field :password %>
    </fieldset>
    <fieldset>
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation %>
    </fieldset>
    <div>
      <%= f.submit "Create Account" %>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="contentcontainer">
  <h2> <%= " #{@user.username}'s Page" %> </h2>

  <div>
    <div class="links">
      <h3>Your Links</h3>
      <div>
        <%= link_to "Twitter: #{@user.twitter}" %>
      </div>
      <div>
        <%= link_to "github", "https://github.com/#{@user.github}" %>
      </div>
      <div>
        <%= link_to "email", "mailto:#{@user.email}?subject:hello" %>
      </div>
      <div>
        <%= link_to "rss feed", "/posts.rss" %>
      </div>
    </div>
  </div>


  <div class="userposts">
    <h3><%="#{@user.username}'s Blog Posts" %></h3>
    <ul>
      <% @posts.each do |post| %>
        <fieldset>
          <li>
            Post Title: <%= link_to post.title, post_path(post) %>
          </li>
          <li>
            Post Created At: <time>
              <%= post.created_at.to_formatted_s(:day_month_year) %>
            </time>
          </li>
        </fieldset>
      <% end %>
      <%= paginate @posts %>
    </ul>
  </div>
</div>